#!/usr/bin/env node

const {
  DEFAULT_SALT,
  detectUserId,
  parseMinStat,
  rollWithSalt,
  searchSalts,
  STAT_NAMES,
} = require('./buddy-core.js');

function printUsage() {
  console.log(`buddy-lab

Usage:
  node tools/buddy-lab.js preview [--user-id <id>] [--salt <salt>]
  node tools/buddy-lab.js search [filters] [--total <n>] [--salt-prefix <p>]

Commands:
  preview     Show the buddy generated by userId + salt
  search      Search candidate salts and print matches

Common flags:
  --user-id <id>       Override detected userId/accountUuid
  --salt <salt>        Salt to preview
  --total <n>          Search attempts, default 100000
  --salt-prefix <p>    Prefix for generated salts, default "lab-"
  --length <n>         Exact generated salt length, default current salt length

Filters for search:
  --species <name>
  --rarity <tier>
  --eye <glyph>
  --hat <name>
  --shiny
  --min-stat <NAME:value>

Examples:
  node tools/buddy-lab.js preview
  node tools/buddy-lab.js preview --salt friend-2026-401
  node tools/buddy-lab.js search --species owl --rarity rare --total 500000
  node tools/buddy-lab.js search --shiny --min-stat CHAOS:80
`);
}

function parseArgs(argv) {
  const args = { _: [] };
  for (let i = 0; i < argv.length; i += 1) {
    const token = argv[i];
    if (!token.startsWith('--')) {
      args._.push(token);
      continue;
    }
    const key = token.slice(2);
    if (key === 'shiny') {
      args.shiny = true;
      continue;
    }
    const value = argv[i + 1];
    if (value === undefined || value.startsWith('--')) {
      throw new Error(`Missing value for --${key}`);
    }
    args[key] = value;
    i += 1;
  }
  return args;
}

function printPreview(userId, salt, result) {
  console.log(JSON.stringify({
    userId,
    salt,
    buddy: result,
  }, null, 2));
}

function runPreview(args) {
  const userId = args['user-id'] || detectUserId();
  const salt = args.salt || DEFAULT_SALT;
  const result = rollWithSalt(userId, salt);
  printPreview(userId, salt, result);
}

function runSearch(args) {
  const userId = args['user-id'] || detectUserId();
  const total = Number(args.total || 100000);
  if (!Number.isFinite(total) || total <= 0) {
    throw new Error(`Invalid --total value: ${args.total}`);
  }
  const prefix = args['salt-prefix'] || 'lab-';
  const length = Number(args.length || (args.salt ? args.salt.length : DEFAULT_SALT.length));
  if (!Number.isFinite(length) || length <= 0) {
    throw new Error(`Invalid --length value: ${args.length}`);
  }
  const minStat = parseMinStat(args['min-stat']);
  const filters = {
    species: args.species,
    rarity: args.rarity,
    eye: args.eye,
    hat: args.hat,
    shiny: !!args.shiny,
    minStat,
  };
  const matches = searchSalts({ userId, total, prefix, length, filters, maxMatches: 20 });

  console.log(JSON.stringify({
    userId,
    searched: total,
    filters: {
      ...filters,
      minStat: minStat ? `${minStat.name}:${minStat.threshold}` : undefined,
    },
    matches,
  }, null, 2));
}

function main() {
  try {
    const args = parseArgs(process.argv.slice(2));
    const command = args._[0];
    if (!command || command === 'help' || command === '--help') {
      printUsage();
      return;
    }
    if (command === 'preview') {
      runPreview(args);
      return;
    }
    if (command === 'search') {
      runSearch(args);
      return;
    }
    throw new Error(`Unknown command: ${command}`);
  } catch (error) {
    console.error(error.message);
    process.exitCode = 1;
  }
}

main();
